spring:
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 5
      maxPoolSize: 10
      keepAliveSeconds: 60
      queueCapacity: 100
      waitForTasksToCompleteOnShutdown: true
      awaitTerminationSeconds: 30
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000
    database: 10
  datasource:
#    url: jdbc:mysql://119.23.242.234:9306/yyg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/yyg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cachePrepStmts: true
    
#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml

logging:
  config: classpath:log4j2.xml

mapper:
  identity: MYSQL

filePath: http://119.23.242.234:9092

robot:
  point: 0.01
  people: 5
  lowsize: 55
