server:
  port: 8088
spring:
  profiles:
    active: test  #合并 application-test.yml 中的配置参数
  messages:
    basename: i18n/messages
    cache-second: 3600
    encoding: UTF-8
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000
    database: 10
#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml

logging:
  config: classpath:log4j2.xml

mapper:
  identity: MYSQL

filePath:

staticPath:  D:/static/common/

robot:
  point: 0.01
  people: 5
  lowsize: 55

mall_id: cabf5fdd363bbb73209a32d4ce12b65a

shared_key: t8oO2DMFX8UY

ratio: 100



